require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'zampi-dev' do
  config = use_native_modules!
  # pod  "@react-native-firebase/app": "^12.4.0",
  # pod  "@react-native-firebase/auth": "^11.4.1",
  # pod  "@react-native-firebase/messaging": "^11.4.1",
  # pod  "@react-native-firebase/remote-config": "^11.4.1",
  # pod  "@react-native-firebase/storage": "^12.4.0",
   
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end