# # Uncomment the next line to define a global platform for your project
# # platform :ios, '9.0'

# target 'zampi-dev' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!
#   # use_modular_headers!


#   # Pods for zampi-dev

# end

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'zampi-dev' do
  config = use_native_modules!
  # pod 'Firebase/Core', '~>5.20.2'

  # pod  "@react-native-firebase/app": "^12.4.0",
  # pod  "@react-native-firebase/auth": "^11.4.1",
  # pod  "@react-native-firebase/messaging": "^11.4.1",
  # pod  "@react-native-firebase/remote-config": "^11.4.1",
  # pod  "@react-native-firebase/storage": "^12.4.0",
   
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
    end
end
